import { mkdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join, win32 } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { WINDOWS_LAUNCHER_NAME } from "./paths.mjs";

const execFileAsync = promisify(execFile);
const POWERSHELL = "powershell.exe";
const LAUNCHER_NAME = WINDOWS_LAUNCHER_NAME;

// --- Pure builders (unit-testable; no I/O) ----------------------------------

// The shortcut runs a tiny .cmd wrapper rather than the packaged exe directly:
// Explorer blocks user shortcuts that point into the read-only WindowsApps
// tree, and the wrapper lets the Node CLI re-discover the (version-named) MSIX
// path on every launch so auto-updates never stale the shortcut.
export function buildCmdWrapper({ nodeExe, cliScript, port }) {
  const at = Number(port) || 9333;
  const toWin = (p) => String(p).replaceAll("/", "\\");
  return [
    "@echo off",
    "rem Generated by explodex — launches Codex with plugins injected.",
    `set "EXPLODEX_DEBUG_PORT=${at}"`,
    `"${toWin(nodeExe)}" "${toWin(cliScript)}" --launch`,
    "if errorlevel 1 pause",
    "",
  ].join("\r\n");
}

// PowerShell that turns a .cmd into a Start-Menu/Desktop .lnk via WScript.Shell.
export function buildShortcutScript({ cmdPath, lnkPath, iconLocation, description }) {
  const q = (s) => String(s).replace(/'/g, "''");
  return [
    `$ws = New-Object -ComObject WScript.Shell`,
    `$sc = $ws.CreateShortcut('${q(lnkPath)}')`,
    `$sc.TargetPath = '${q(cmdPath)}'`,
    `$sc.WorkingDirectory = '${q(win32.dirname(cmdPath))}'`,
    iconLocation ? `$sc.IconLocation = '${q(iconLocation)}'` : `$sc.IconLocation = '%SystemRoot%\\System32\\shell32.dll,137'`,
    description ? `$sc.Description = '${q(description)}'` : `$sc.Description = 'Codex with Explodex plugins'`,
    `$sc.Save()`,
  ].join("; ");
}

// --- Installed-mode side effects --------------------------------------------

export function startMenuLnkPath(home = homedir()) {
  // %APPDATA%\Microsoft\Windows\Start Menu\Programs
  return join(home, "AppData", "Roaming", "Microsoft", "Windows", "Start Menu", "Programs", `${LAUNCHER_NAME}.lnk`);
}

export function desktopLnkPath(home = homedir()) {
  return join(home, "Desktop", `${LAUNCHER_NAME}.lnk`);
}

export function wrapperCmdPath(home = homedir()) {
  return join(home, ".explodex", "bin", `${LAUNCHER_NAME}.cmd`);
}

export async function installLauncher({
  home = homedir(),
  port = Number(process.env.EXPLODEX_DEBUG_PORT ?? 9333),
  nodeExe = "node",
  cliScript,
  desktop = true,
  startMenu = true,
} = {}) {
  if (!cliScript) throw new Error("installLauncher needs cliScript (absolute path to bin/explodex.mjs)");
  const cmdPath = wrapperCmdPath(home);
  await mkdir(win32.dirname(cmdPath), { recursive: true });
  await writeFile(cmdPath, buildCmdWrapper({ nodeExe, cliScript, port }), "utf8");

  const targets = [];
  if (startMenu) targets.push(startMenuLnkPath(home));
  if (desktop) targets.push(desktopLnkPath(home));
  for (const lnk of targets) {
    await mkdir(win32.dirname(lnk), { recursive: true });
    await execFileAsync(POWERSHELL, ["-NoProfile", "-NonInteractive", "-Command", buildShortcutScript({ cmdPath, lnkPath: lnk })], { windowsHide: true });
  }
  return { path: cmdPath, shortcuts: targets };
}

export async function uninstallLauncher({ home = homedir() } = {}) {
  const targets = [wrapperCmdPath(home), startMenuLnkPath(home), desktopLnkPath(home)];
  const removed = targets.filter((p) => existsSync(p));
  for (const p of removed) await rm(p, { force: true });
  return { path: wrapperCmdPath(home), removed: removed.length > 0, removedPaths: removed };
}
